#!/usr/bin/env bash
DOCKER_SOCK="/var/run/docker.sock"
TARGET_USER="$(whoami)"

# Check if the Docker socket exists
if [ ! -S "$DOCKER_SOCK" ]; then
    echo "Error: Docker socket $DOCKER_SOCK not found."
    exit 1
fi

# Check if the owner of the Docker socket is the target user
owner=$(stat -c "%U" "$DOCKER_SOCK")

if [ "$owner" = "$TARGET_USER" ]; then
  lazydocker
else
    # Adjust ownership using sudo
    sudo chown "$TARGET_USER" "$DOCKER_SOCK"
    sudo chmod u+rw "$DOCKER_SOCK"
    if [ $? -eq 0 ]; then
      lazydocker
    else
        echo "Error adjusting ownership."
        exit 1
    fi
fi

