#!/usr/bin/env fish
set DOCKER_SOCK "/var/run/docker.sock"
set TARGET_USER "sul"

# Check if the Docker socket exists
if not test -S "$DOCKER_SOCK"
    echo "Error: Docker socket $DOCKER_SOCK not found."
    exit 1
end

# Check if the owner of the Docker socket is the target user
set owner (stat -c "%U" $DOCKER_SOCK)

if [ "$owner" = "$TARGET_USER" ]
    lazydocker
else
    # Adjust ownership using sudo
    sudo chown $TARGET_USER $DOCKER_SOCK
    sudo chmod u+rw $DOCKER_SOCK
    if test $status -eq 0
        lazydocker
    else
        echo "Error adjusting ownership."
        exit 1
    end
end

